package:
  name: ont-fast5-api
  version: "1.1.1"

source:
  url: https://files.pythonhosted.org/packages/b4/21/6f2d5c2897b7138b404161e3b0f3a4f991f3c9d7dc2026f5d3fbe9c8023d/ont-fast5-api-1.1.1.tar.gz
  sha256: 48353956e2300a74dd72bf2e05781312bdeb373cd86072b0a10227819a80025c

build:
  noarch: python
  number: 0

requirements:
  host:
    - python
    - setuptools
    - h5py
    - numpy >=1.8.1
    - progressbar33

  run:
    - python
    - h5py
    - numpy >=1.8.1
    - progressbar33

test:
  imports:
    - ont_fast5_api
    - ont_fast5_api.analysis_tools
  commands:
    - multi_to_single_fast5 -h

about:
  home: https://github.com/nanoporetech/ont_fast5_api
  license: Mozilla Public License 2.0 (MPL 2.0)
  summary: 'Oxford Nanopore Technologies fast5 API software'
  license_family: OTHER
