package:
  name: ont-fast5-api
  version: "1.2.0"

source:
  url: https://files.pythonhosted.org/packages/e2/52/460835685daebaee4d7e014ad208f30bb9617eec55d14733e1bbc6705f5e/ont-fast5-api-1.2.0.tar.gz
  sha256: e3dd5c85c2113658562e4a3e1b1a95f552ac8b761b3ea8caa45ca5217016d5b2

build:
  noarch: python
  number: 0

requirements:
  host:
    - python
    - setuptools
    - h5py
    - numpy >=1.8.1
    - progressbar33

  run:
    - python
    - h5py
    - numpy >=1.8.1
    - progressbar33

test:
  imports:
    - ont_fast5_api
    - ont_fast5_api.analysis_tools
  commands:
    - multi_to_single_fast5 -h

about:
  home: https://github.com/nanoporetech/ont_fast5_api
  license: Mozilla Public License 2.0 (MPL 2.0)
  summary: 'Oxford Nanopore Technologies fast5 API software'
  license_family: OTHER
